sylius_resource:
    resources:
        chat.chat:
            driver: doctrine/orm
            classes:
                model: ChatBundle\Entity\Chat

fos_rest:
    disable_csrf_role: ROLE_API
    view:
        formats:
            json: true
            xml:  true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
